import assert from 'node:assert/strict';
import {authEndpoint,accountIdentity} from './server/auth.mjs';
import {localDatabase} from './server/local-db.mjs';
const DB=localDatabase(':memory:'),base='https://planwithgoplan.com',env={DB,SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'test-publishable'};
let called=0,serial=0;const user={id:'subject-1',email:'student@example.com',email_confirmed_at:new Date().toISOString()};const options={authFetcher:async(url,init)=>{called++;const body=JSON.parse(init.body);if(url.endsWith('/otp'))return Response.json({});if(url.endsWith('/user')){assert.equal(init.method,'PUT');assert.match(init.headers.Authorization,/^Bearer test-ticket-/);return Response.json(user);}if(url.includes('grant_type=password'))return body.password==='test passphrase only'?Response.json({user}):Response.json({error:'Invalid credentials'},{status:400});if(body.token==='111111')return Response.json({user,access_token:'test-ticket-'+(++serial)});return Response.json({error:'Invalid code'},{status:400});}};
const req=(path,body,extra={})=>new Request(base+'/api/auth/'+path,{method:'POST',headers:{Origin:base,'Content-Type':'application/json',...extra},body:JSON.stringify(body)});
assert.equal((await authEndpoint(req('send',{email:'invalid'}),env,options)).status,400);
assert.equal((await authEndpoint(req('send',{email:'student@example.com'},{Origin:'https://evil.example'}),env,options)).status,403);assert.equal(called,0);
assert.equal((await authEndpoint(req('send',{email:'student@example.com'}),env,options)).status,200);assert.equal((await authEndpoint(req('send',{email:'student@example.com'}),env,options)).status,429);
await DB.prepare('INSERT INTO student_profiles(id,email,first_name,last_name,created_at,last_seen_at,consent_version) VALUES(?,?,?,?,?,?,?)').bind('legacy-id','student@example.com','Amina','Tester',Date.now(),Date.now(),'old').run();
assert.equal((await authEndpoint(req('verify',{email:'student@example.com',code:'222222'}),env,options)).status,400);
const verified=await authEndpoint(req('verify',{email:'student@example.com',code:'111111'}),env,options);assert.equal(verified.status,200);assert.deepEqual(await verified.json(),{verified:true});const ticketCookie=verified.headers.get('Set-Cookie').split(';')[0];
assert.equal(await accountIdentity(new Request(base,{headers:{Cookie:ticketCookie}}),env),null);
assert.equal((await authEndpoint(req('password',{email:user.email,password:'test passphrase only'}),env,options)).status,401);
assert.equal((await authEndpoint(req('password',{email:user.email,password:'short'},{Cookie:ticketCookie}),env,options)).status,400);
const r=await authEndpoint(req('password',{email:user.email,password:'test passphrase only'},{Cookie:ticketCookie}),env,options);assert.equal(r.status,200);const cookie=r.headers.get('Set-Cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);assert.match(cookie,/SameSite=Lax/);const raw=cookie.split(';')[0];
assert.deepEqual({...await accountIdentity(new Request(base,{headers:{Cookie:raw}}),env)},{id:'legacy-id',email:'student@example.com'});
assert.equal(await accountIdentity(new Request(base,{headers:{'oai-authenticated-user-id':'forged','oai-authenticated-user-email':'student@example.com'}}),env),null);
assert.equal(await accountIdentity(new Request(base,{headers:{Cookie:'__Host-goplan-session='+'0'.repeat(64)}}),env),null);
assert.ok(!(await DB.prepare('SELECT token_hash FROM auth_sessions').first()).token_hash.includes(raw.split('=')[1]));
assert.equal((await authEndpoint(req('signout',{}, {Cookie:raw}),env,options)).status,200);assert.equal(await accountIdentity(new Request(base,{headers:{Cookie:raw}}),env),null);
assert.equal((await authEndpoint(req('send',{email:'other@example.com'}),{DB},options)).status,503);
assert.equal((await authEndpoint(req('password',{email:user.email,password:'test passphrase only'},{Cookie:ticketCookie}),env,options)).status,401);
assert.equal((await authEndpoint(req('login',{email:user.email,password:'wrong'}),env,options)).status,400);
const login=await authEndpoint(req('login',{email:user.email,password:'test passphrase only'}),env,options);assert.equal(login.status,200);const oldSession=login.headers.get('Set-Cookie').split(';')[0];
const reset=await authEndpoint(req('verify',{email:user.email,code:'111111'}),env,options);const resetCookie=reset.headers.get('Set-Cookie').split(';')[0];
assert.equal((await authEndpoint(req('password',{email:user.email,password:'new test passphrase'},{Cookie:resetCookie}),env,options)).status,200);
assert.equal(await accountIdentity(new Request(base,{headers:{Cookie:oldSession}}),env),null);
const expired=await authEndpoint(req('verify',{email:user.email,code:'111111'}),env,options);await DB.prepare('UPDATE auth_password_tickets SET expires_at=0').run();assert.equal((await authEndpoint(req('password',{email:user.email,password:'new test passphrase'},{Cookie:expired.headers.get('Set-Cookie').split(';')[0]}),env,options)).status,401);
DB.close();console.log('Email authentication: origin checks, send limits, invalid codes, verified legacy migration, secure cookie, hashed sessions, forged identity rejection, logout, password login, verified setup, ticket replay/expiry, password reset session revocation and missing configuration passed.');
