const $=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString(),names={setup:'Starting point',direction:'Your direction',courses:'Course choices',targets:'Company & exchange targets',pace:'Study pace',replan:'Course changes',change:'Plan updates',question:'Adviser questions',plan_saved:'Plans saved',plan_updated:'Plan revisions accepted',targets_updated:'Destinations updated',excel_requested:'Excel downloads requested'};
let snapshot,reports=[],reportsLoaded=false,selectedReport,refreshVersion=0,currentTab='overview',students=[],studentsTotal=0,studentsLoaded=false;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const local=location.hostname==='127.0.0.1'||location.hostname==='localhost';
if(local)$('signout').hidden=true;
async function api(path,body){const r=await fetch('/api/admin/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin',signal:AbortSignal.timeout(25000)});let d;try{d=await r.json();}catch{throw Error('Unexpected server response. Refresh and try again.');}if(!r.ok){if(r.status===401&&!local){$('error').replaceChildren(el('span','Your owner session expired. '));const a=el('a','Sign in again');a.href='/signin.html?next=admin';a.target='_top';$('error').append(a);$('error').hidden=false;}throw Error(d.error||'The request could not be completed.');}return d;}
function card(title,value,detail,style){const n=el('article',undefined,'card '+(style||''));n.append(el('p',title),el('strong',value),el('small',detail));return n;}
function filtered(){return (snapshot?.rows||[]).filter(r=>$('channel').value==='all'||r.channel===$('channel').value);}
function render(){if(!snapshot)return;const rows=filtered(),t={operations:0,success:0,error:0,cached:0,duration:0,calls:0,input:0,output:0},events=new Map(),stages=new Map(),days=new Map();
 for(const r of rows){if(r.kind==='event'){events.set(r.stage,(events.get(r.stage)||0)+r.count);continue;}t.operations+=r.count;t[r.outcome]+=r.count;t.duration+=r.duration_ms;t.calls+=r.provider_calls;t.input+=r.input_tokens;t.output+=r.output_tokens;const s=stages.get(r.stage)||{success:0,error:0,cached:0,duration:0};s[r.outcome]+=r.count;s.duration+=r.duration_ms;stages.set(r.stage,s);const d=days.get(r.day)||{total:0,errors:0};d.total+=r.count;if(r.outcome==='error')d.errors+=r.count;days.set(r.day,d);}
 const processed=t.success+t.error,rate=processed?(100*t.success/processed).toFixed(1)+'%':'—',time=processed?(t.duration/processed/1000).toFixed(1)+'s':'—';
 $('cards').replaceChildren(card('Adviser operations',fmt(t.operations),'Requests, including cached answers','primary'),card('Plans saved',fmt(events.get('plan_saved')),'Save events · not unique students'),card('Successful responses',rate,fmt(t.error)+' failed operations · excludes cache'),card('Average response',time,'Includes retries · excludes cache'));
 $('health-cards').replaceChildren(card('Successful operations',fmt(t.success),rate+' success rate','primary'),card('Failed operations',fmt(t.error),'Adviser requests that returned an error'),card('Cached answers',fmt(t.cached),'Reused without another model call'),card('Provider calls',fmt(t.calls),'Includes retries and research rounds'));
 const max=Math.max(1,...[...days.values()].map(d=>d.total));$('chart').replaceChildren();$('daily').replaceChildren();
 for(let i=0;i<snapshot.days;i++){const d=new Date(snapshot.since+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+i);const date=d.toISOString().slice(0,10),value=days.get(date)||{total:0,errors:0};const tr=el('tr');[date,fmt(value.total),fmt(value.errors)].forEach(x=>tr.append(el('td',x)));$('daily').append(tr);if(t.operations){const wrap=el('div',undefined,'day'),bar=el('div',undefined,'bar');wrap.title=date+': '+value.total+' operations, '+value.errors+' failed';bar.style.height=Math.max(2,value.total/max*155)+'px';wrap.append(bar,el('small',i===0||i===snapshot.days-1?date.slice(5):''));$('chart').append(wrap);}}
 if(!t.operations)$('chart').append(el('p','No adviser activity recorded for this period and channel. New activity will appear after refresh.','empty'));
 $('chart').setAttribute('aria-label',fmt(t.operations)+' adviser operations in the selected period. A daily data table is available below.');
 $('stages').replaceChildren(...[...stages].map(([key,s])=>{const tr=el('tr');[names[key]||key,fmt(s.success),fmt(s.error),fmt(s.cached),s.success+s.error?(s.duration/(s.success+s.error)/1000).toFixed(1)+'s':'—'].forEach(x=>tr.append(el('td',x)));return tr;}));
 if(!stages.size){const tr=el('tr'),td=el('td','No adviser activity recorded.');td.colSpan=5;tr.append(td);$('stages').append(tr);}
 $('events').replaceChildren(...['plan_saved','plan_updated','targets_updated','excel_requested'].map(k=>eventRow(names[k],fmt(events.get(k)))));
 $('tokens').replaceChildren(eventRow('AI provider calls',fmt(t.calls)),eventRow('Input tokens',fmt(t.input)),eventRow('Output tokens',fmt(t.output)));
 const pending=snapshot.reports.filter(r=>r.status==='pending').reduce((s,r)=>s+r.count,0);$('pending-count').textContent=pending?fmt(pending):'';
 $('insights').replaceChildren(el('p',pending?`${fmt(pending)} feedback reports await review. These cover all channels and dates.`:'No pending reports in the current retained inbox.'),el('p',t.error?`${fmt(t.error)} adviser operations failed. Check “Adviser health” for the planning tasks affected.`:t.operations?'No failed adviser operations recorded in this selection.':'Run a student test to start measuring adviser activity.'));
 $('limits').replaceChildren(...snapshot.limits.map(x=>el('li',x)));
 $('status').textContent=(snapshot.enabled?'Live measurement enabled':'Measurement disabled')+' · Updated '+new Date(snapshot.generatedAt).toLocaleString();$('export').disabled=false;$('export-json').disabled=false;
}
function eventRow(label,value){const n=el('div',undefined,'event');n.append(el('span',label),el('strong',value));return n;}
async function refresh(){const version=++refreshVersion;$('refresh').disabled=true;$('error').hidden=true;try{const data=await api('analytics?days='+$('period').value);if(version!==refreshVersion)return;snapshot=data;render();if(currentTab==='feedback')await loadReports();if(currentTab==='students')await loadStudents();}catch(e){if(version!==refreshVersion)return;if($('error').hidden){$('error').textContent=e.message;$('error').hidden=false;}$('status').textContent=snapshot?'Showing the last successful snapshot; these numbers are not fresh.':'No data loaded.';}finally{if(version===refreshVersion)$('refresh').disabled=false;}}
const titles={students:['YOUR REGISTERED COMMUNITY','Students'],overview:['YOUR MVP AT A GLANCE','Overview'],reliability:['EVERY RESPONSE MATTERS','Adviser health'],feedback:['THE STUDENT FEEDBACK LOOP','Feedback'],data:['UNDERSTAND YOUR MEASUREMENTS','Your data & exports.']};
function showTab(tab){currentTab=tab;document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!=='view-'+tab);document.querySelectorAll('nav [data-tab]').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false'));$('section-label').textContent=titles[tab][0];$('page-title').textContent=titles[tab][1];if(tab==='feedback'&&!reportsLoaded)loadReports();if(tab==='students'&&!studentsLoaded)loadStudents();}
async function loadReports(){$('report-error').hidden=true;$('report-status').textContent='Loading submitted reports…';try{const d=await api('reports');reports=d.reports;reportsLoaded=true;renderReports();}catch(e){$('report-error').textContent=e.message;$('report-error').hidden=false;$('report-status').textContent=reportsLoaded?'Showing previously loaded reports.':'Reports could not be loaded.';}}
function renderReports(){const filtered=reports.filter(r=>$('report-filter').value==='all'||r.status===$('report-filter').value);$('report-status').textContent=`${filtered.length} shown · latest ${reports.length} retained reports (maximum 100). Period and channel filters do not apply to the inbox.`;$('report-list').replaceChildren();for(const r of filtered){const box=el('article',undefined,'panel report'),content=el('div'),p=r.report;content.append(el('span',r.status,'pill'),el('h3',(names[p.stage]||p.stage)+' · '+p.academic.program),el('p',p.issue,'report-preview'),el('p',new Date(r.createdAt).toLocaleString()+' · '+p.category+' · '+(r.improve?'Improvement sharing allowed':'Report review only'),'report-meta'));const button=el('button','Review report');button.onclick=()=>openReview(r);box.append(content,button);$('report-list').append(box);}if(!filtered.length)$('report-list').append(el('div','No reports match this filter. Student mistake reports will appear here when submitted.','panel empty'));}
function openReview(r){selectedReport=r;$('review-form').reset();$('review-error').hidden=true;$('review-status').textContent='';$('correction-fields').hidden=true;for(const id of ['correction','source-url','evidence-checked'])$(id).required=false;const n=el('div',undefined,'report-body'),p=r.report;for(const [label,text] of [['Student report',p.issue],['Expected outcome',p.expected||'Not supplied'],['Evidence supplied by student',p.evidence||'Not supplied'],['Academic context',[p.academic.program,p.academic.track,p.academic.secondTrack,p.academic.minor].filter(Boolean).join(' · ')],['Previous review',r.reviewNote||'No review yet'],['Permission',r.improve?'The student allows verified guidance to inform future advice.':'This student has not agreed to shared guidance.'],['Expires',new Date(r.expiresAt).toLocaleDateString()]])n.append(el('strong',label),el('p',text));$('report-detail').replaceChildren(n);$('review-dialog').showModal();}
$('decision').onchange=()=>{const yes=$('decision').value==='confirmed';$('correction-fields').hidden=!yes;$('correction').required=yes;$('correction').minLength=yes?20:0;$('source-url').required=yes;$('evidence-checked').required=yes;};
$('close-review').onclick=()=>$('review-dialog').close();
$('review-form').onsubmit=async e=>{e.preventDefault();if(!selectedReport)return;$('save-review').disabled=true;$('review-error').hidden=true;$('review-status').textContent='Saving your review…';try{await api('review',{id:selectedReport.id,status:$('decision').value,note:$('review-note').value,correction:$('correction').value,source:{url:$('source-url').value},evidenceChecked:$('evidence-checked').checked});$('review-dialog').close();await loadReports();await refresh();}catch(e){$('review-error').textContent=e.message;$('review-error').hidden=false;$('review-status').textContent='Not saved. Your review text is still here.';}finally{$('save-review').disabled=false;}};
function download(type){if(!snapshot)return;const a=el('a');a.href='/api/admin/export?days='+snapshot.days+'&channel='+encodeURIComponent($('channel').value)+'&format='+type;a.download='GoPlan-usage.'+type;document.body.append(a);a.click();a.remove();}
$('export').onclick=()=>download('csv');$('export-json').onclick=()=>download('json');$('refresh').onclick=refresh;$('period').onchange=refresh;$('channel').onchange=render;$('report-filter').onchange=renderReports;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));refresh();

async function loadStudents(){$('student-error').hidden=true;$('student-count').textContent='Loading profiles…';try{const data=await api('students');students=data.students;studentsTotal=data.total;studentsLoaded=true;renderStudents();}catch(e){$('student-error').textContent=e.message;$('student-error').hidden=false;$('student-count').textContent='Profiles could not be refreshed.';}}
function renderStudents(){const q=$('student-search').value.trim().toLowerCase(),rows=students.filter(s=>(s.firstName+' '+s.lastName+' '+s.email).toLowerCase().includes(q));$('student-count').textContent=fmt(studentsTotal)+' registered profiles · showing '+rows.length+' of the latest '+students.length+' (maximum 200).';$('student-rows').replaceChildren(...rows.map(s=>{const tr=el('tr');[s.firstName+' '+s.lastName,s.email,new Date(s.createdAt).toLocaleDateString(),new Date(s.lastSeenAt).toLocaleString()].forEach(v=>tr.append(el('td',v)));return tr;}));if(!rows.length){const tr=el('tr'),td=el('td','No profiles match. Students appear after creating their GoPlan profile.');td.colSpan=4;tr.append(td);$('student-rows').append(tr);}}
$('student-search').oninput=renderStudents;

$('signout').onclick=async()=>{const r=await fetch('/api/auth/signout',{method:'POST',credentials:'same-origin'});if(r.ok)location.assign('/signin.html?next=admin');else{$('error').textContent='Could not sign out. Please retry.';$('error').hidden=false;}};
