"""Reviewed program-table transcriptions; citations use PDF page numbers."""
def graduate_programs():
    def src(page): return {'file':'aui academic catalogue.pdf','page':page,'edition':'2025–2026'}
    def req(cid,title,page,credits=3,**kw): return {'id':cid.lower(),'code':cid,'title':title,'credits':credits,'category':'Graduate core','source':src(page),'choice':False,'options':[],**kw}
    def choice(ident,title,options,page,**kw): return {'id':ident,'title':title,'credits':3,'category':'Graduate elective','source':src(page),'choice':True,'options':options.split() if isinstance(options,str) else options,**kw}
    def courses(rows,page):return [req(cid,title,page) for cid,title in rows]
    def program(pid,name,page,requirements,notes,admission,conflicts=(),tracks=(),credits=30):
        return {'id':pid,'name':name,'level':'graduate','degreeCredits':{'min':credits,'max':credits},'edition':'2025–2026','source':src(page),'requirements':requirements,'tracks':list(tracks),'overrides':{},'notes':notes,'admissionNotes':[{'text':admission,'source':src(page)}],'conflicts':[{'field':'Source difference','details':x,'sources':[src(page)]} for x in conflicts]}
    def finaltracks(pid,page,corecodes,sem=False):
        codes=['SEM5333','SEM5643'] if sem else ['CSC5333','CSC5343']
        result=[]
        for cid,title in zip(codes,['Master thesis','Final project']):
            first=f'{pid}-{cid}-first'; second=f'{pid}-{cid}-second'
            programcodes=corecodes+(['CSC5354','CSC5360','CSC5376'] if pid=='MSBDA' else [])
            r1=req(cid,title+' · first 3-credit registration',page,id=first,credits=3,rule={'all':[],'minProgramCourses':4,'programCourseCodes':programcodes,'review':True},repeatable=True)
            r2=req(cid,title+' · second 3-credit registration',page,id=second,credits=3,rule={'all':[],'minProgramCourses':4,'programCourseCodes':programcodes,'previousId':first,'review':True},repeatable=True)
            result.append({'id':cid,'name':title,'replacesGroup':'culminating','source':src(page),'requirements':[r1,r2]})
        return result
    sse_notes=['Thesis/final project: 6 credits across two consecutive semesters. A summer registration can carry at most 3 of these credits; the remaining 3 must be in Fall or Spring. Confirm the registration code with the coordinator.','Degree CGPA ≥3.0; at least B− in every counted course. Admission may assign additional undergraduate foundation courses; those are not included in the 30 degree credits.']
    se=courses([('CSC5301','Advanced Database Systems and Data Warehousing'),('CSC5338','Human Computer Interaction / UX Design'),('CSC5356','Advanced Data Engineering and Visualization'),('CSC5358','Blockchain Application Development'),('CSC5360','Agile Digital Project Management'),('CSC5361','Software Architecture and Design'),('CSC5373','Cloud and Edge Computing'),('CSC5382','AI for Digital Transformation')],350)
    energy=courses([('SEM5312','Smart-Grid and Grid-Connected Systems'),('SEM5314','Environment, Sustainability, and Energy'),('SEM5316','Energy Markets, Policy, and Regulation'),('SEM5318','Fundamentals of Electric Vehicles and Infrastructures'),('SEM5321','Energy Management'),('SEM5323','Energy Efficiency in Buildings'),('SEM5325','Renewable Energy Project Engineering'),('SEM5327','Energy Economics and Finance')],351)
    bda=courses([('CSC5301','Advanced Database Systems and Data Warehousing'),('CSC5341','Inferential Statistics'),('CSC5345','Advanced Data Mining and Machine Learning'),('CSC5351','Computational Neural Networks and Deep Learning'),('CSC5355','Advanced Big Data Environment and Application'),('CSC5356','Advanced Data Engineering and Visualization')],352)
    programs=[
      program('MSSE','Master of Science in Software Engineering',349,se,sse_notes,'Bachelor in computer science or a closely related discipline. Standard SSE admissions and foundation requirements apply.', ['Program table p350 uses CSC 5373, while the uploaded MSSE sheet and course description use CSC 5374 for Cloud and Edge Computing.','Program requirements p349 name CSC 5333/5343 as 6-credit culminating work, whereas individual course entries use other credit/code variants. Two 3-credit registrations are planning blocks, subject to coordinator confirmation.'],finaltracks('MSSE',349,[r['code'] for r in se])),
      program('MSSEM','Master of Science in Sustainable Energy Management',350,energy,sse_notes,'Bachelor in engineering; formal application and selection based on English, GPA, capstone and possible experience/interview. Up to 24 foundation credits may be assigned.', ['Current p351 course list replaces the different SEM course codes and titles in the older supplied program sheet.'],finaltracks('MSSEM',351,[r['code'] for r in energy],True)),
      program('MSBDA','Master of Science in Big Data Analytics',352,bda+[choice('msbda-elective-1','Big Data elective 1','CSC5354 CSC5360 CSC5376',352),choice('msbda-elective-2','Big Data elective 2','CSC5354 CSC5360 CSC5376',352)],sse_notes,'Engineering, CS, data science or related bachelor; mathematics or BA graduates with a CS minor are also listed.', ['The current catalog requires six core courses plus two electives, replacing the eight mandatory courses in the older sheet.'],finaltracks('MSBDA',352,[r['code'] for r in bda]))]
    dma=courses([('GBU5313','Data Mining'),('MKT5302','Fundamentals of Digital and Social Media Marketing'),('MKT5304','Applied Marketing Models'),('MKT5305','Advanced Marketing Management'),('MKT5307','Marketing Research'),('MKT5311','Web and Social Media Marketing and Analytics'),('MKT5312','Digital Marketing Research Project'),('MKT5313','Digital Marketing Capstone')],317)
    dma += [choice(f'msdma-elective-{i}',f'Digital Marketing elective {i}','GBU5308 GBU5314 MKT5301 MKT5303 MKT5306 MKT5308 MKT5310 MKT5316 MKT5399',317) for i in [1,2]]
    programs.append(program('MSDMA','Master of Science in Digital Marketing and Analytics',316,dma,['Eight core courses (24 credits) and two electives (6 credits), p317. Up to 12 business foundation credits may be assigned and are outside the degree total.','Full-time in Ifrane. Degree CGPA ≥3.0. The exit section says minimum B in all courses; the structure section says repeat courses below B−. Confirm the applicable grade threshold with the program.'],'Bachelor or equivalent with minimum B standing; some professional experience; interview and complete application; GMAT highly recommended. English evidence is required where applicable.',['GBU 5308 is an elective in p317, although it is mandatory in the older supplied sheet. The current plan has 8 core courses and 2 electives.']))
    com=courses([('COM5311','Human-Centered Design'),('COM5312','Public Relations & Digital Media'),('COM5313','Advanced Media & Communication Theory'),('SSC5302','Thesis I: Multidisciplinary Research Design & Methods')],325)
    com += [choice('macdm-final','Thesis II seminar or applied practicum','COM5391 COM5392',325,rule={'all':['SSC5302'],'review':True})]
    com += [choice(f'macdm-option-{i}',f'Communication elective {i}','COM5303 COM5302 COM5315 COM5316 COM5317 COM5318 COM5398 COM5399',325) for i in range(1,6)]
    programs.append(program('MACDM','Master of Arts in Communication and Digital Media',323,com,['15 required credits + 15 optional credits, catalog p325. The older communication sheet does not define the current program.','Thesis II follows Thesis I in the immediately following summer. Thesis work must be completed in residence at AUI (p326). Intersession offerings are conditional and are not assumed in this planner.','Additional SSAH Research Academy courses may be required: normally 6 credits for non-AUI entrants, 3 for AUI entrants in a different field, with exemptions and committee discretion (pp323–324).'],'AUI graduates: CGPA ≥3.0 and TOEFL ≥550 for regular admission; 500–549 may enter the Language Center. Writing and other application requirements apply; consult pp323–324.'))
    ins=courses([('INS5303','Advanced IR Theory'),('INS5304','Moroccan Foreign Policy'),('INS5306','Diplomatic Negotiation'),('INS5315','International Political Economy'),('SSC5302','Thesis I: Multidisciplinary Research Design & Methods')],329)
    ins += [choice('maisd-final','Thesis II seminar or policy practicum','SSC5310 INS5392',329,rule={'all':['SSC5302'],'review':True})]
    ins += [choice(f'maisd-option-{i}',f'International Studies elective {i}','GEO5311 HIS5328 INS5310 INS5311 INS5313 INS5351 INS5356 PSC5315 PSC5360 SSC5331 SSC5362 FIN5306 FIN5312 ECO5305 ECO5306 ECO5307 MKT5306',329,condition='SBA options require SBA approval. Confirm the ECO course-code/title conflicts in this program table.') for i in range(1,5)]
    programs.append(program('MAISD','Master of Arts in International Studies and Diplomacy',327,ins,['18 core credits + 12 optional credits (p329). Additional Research Academy/foundation work may be assigned outside this total.','Thesis II follows Thesis I in the immediately following summer; thesis courses must be completed at AUI. Confirm practicum timing with the coordinator (p330).'],'AUI graduates: CGPA ≥3.0; TOEFL ≥550 for regular admission, with 500–549 Language Center route. Other admissions routes and writing/application requirements are detailed in pp327–328.',['Optional ECO 5305/5306/5307 titles on p329 differ from their SBA course descriptions. Confirm equivalencies before choosing them.']))
    mba=courses([('ACC5302','Managerial Accounting'),('ECO5305','Managerial Economics'),('FIN5305','Financial Management'),('GBU5306','Business Decision Making and Management Science'),('MGT5305','Organization Behavior and Leadership'),('MGT5306','Strategic Management in Global Markets'),('MIS5301','Managing Information Systems in Organizations'),('MKT5305','Advanced Marketing Management')],304)
    mba.append(req('GBU5020','Research Methodology Seminar',304,0))
    conc=[choice(f'mba-concentration-{i}',f'Approved MBA concentration course {i}',[],305,condition='Choose one coherent concentration and obtain coordinator approval. A course selection alone does not certify the concentration.') for i in range(1,4)]
    tracks=[{'id':'thesis','name':'Thesis track','replacesGroup':'culminating','source':src(309),'requirements':conc+[req('GBU5320','MBA Thesis',309)]}, {'id':'coursework','name':'Non-thesis · four concentration courses','replacesGroup':'culminating','source':src(310),'requirements':conc+[choice('mba-concentration-4','Approved MBA concentration course 4',[],305)]}, {'id':'internship','name':'Non-thesis · concentration and internship','replacesGroup':'culminating','source':src(304),'requirements':conc+[req('INT5301','Graduate Internship',304,rule={'all':[r['code'] for r in mba],'review':True})]}]
    programs.append(program('MBA','Master of Business Administration',302,mba,['36 degree credits, including 24 core credits and a concentration/final route. GBU 5020 is a required zero-credit seminar. See example sequences pp309–310.','Concentrations: Finance, Marketing, Management, Supply Chain Management, Business Analytics and AI, FinTech, or General (pp305–308). Concentration coherence and foundations need individual review.','Internship route: minimum six months full time after coursework. MGT 5306 includes the integrated capstone. Foundations can add up to 12 non-degree credits (p303).'],'Bachelor or equivalent with minimum B standing; application and interview. Non-business entrants may need foundation courses. Check English evidence and program-specific requirements.', ['The p303 thesis-track summary is arithmetically incomplete; the 36-credit structure is clarified by the detailed sample on p309. Foundation-grade wording differs from the general graduate policy.'],tracks,36))
    for p in programs:
        if p['id'] in ['MACDM','MAISD']:
            for r in p['requirements']:
                if r.get('code')=='SSC5302': r['offeredTerms']=['Spring']
                if r['id'] in ['macdm-final','maisd-final']:
                    thesis='COM5391' if p['id']=='MACDM' else 'SSC5310'
                    r['conditionalRules']={thesis:{'offeredTerms':['Summer'],'previousId':'ssc5302','previousSeason':'Spring'}}
                    r['condition']='Only the thesis follows Thesis I in the immediately following summer. Practicum timing requires coordinator confirmation.'
    return programs

def policies():
    def p(title,text,page):return {'title':title,'text':text,'source':{'file':'aui academic catalogue.pdf','page':page}}
    return [p('Your applicable catalog','Degree requirements normally follow the catalog at admission or an eligible later catalog. Operating policies can change independently; ask your advisor which edition applies.',105),p('Undergraduate course load','Normal regular load: five courses and 12–17 credits. Students in good standing with CGPA ≥3.0 may take six courses up to 20 credits. Other conditional routes apply at CGPA ≥2.5; this planner does not assume those approvals.',104),p('Summer planning','This planner conservatively uses at most two courses / seven credits and one laboratory. The catalog permits additional summer-load routes subject to GPA, retakes, graduating status, lab and Language Center conditions; those need individual review.',104),p('Graduate course load','Regular full-time graduate study normally carries 9–12 credits; summer permits two courses up to 7 credits. Foundation and Language Center conditions may alter the plan.',297),p('Graduate admission','A recognized bachelor’s degree, adequate academic preparation and evidence of graduate-study ability are required. General guidance recommends CGPA 3.0; specific programs may impose their own thresholds. A suggested GPA is not an admission guarantee.',32),p('Combined BS/MS','Admission is selective: the catalog includes a direct-entry route for Mention Bien or equivalent, and an in-study route after 48–129 credits with CGPA ≥2.5 and major-area GPA ≥3.0, relevant major credits and faculty recommendations. Approved program pairings and individual approval govern shared credits and waivers.',348),p('Fast-track energy management','Approved BSEMS/BSGE/BSRESE students may count 12 MSSEM credits toward both degrees. BSGE must also take EGR 3392 for its thematic area; BSRESE uses it as a free elective. GPA, grade and approval rules apply.',349),p('Accelerated Bachelor–MBA','Up to 12 MBA core credits may be taken while undergraduate, under formal approval and registration rules; up to nine can count as undergraduate electives depending on the pathway. These courses cannot be taken on exchange. Minimum B− for MBA credit and C for undergraduate credit; consult pp312–314.',312),p('Combined BAIS–MAISD','The combined route has admission after at least 60 credits and CGPA ≥3.0, with ongoing conditions. Catalog p342 states 148 total credits while p164 states 150; confirm the governing plan before assuming waived capstone or shared-credit totals.',342)]
